create table CLASSES 
    (ID INT(4),
    NAME VARCHAR(20), 
    DAY VARCHAR(10), 
    ADDRESS_ID VARCHAR(2), 
    CITY VARCHAR(20), 
    START_TIME VARCHAR(5),
    START_DATE DATE,
    LENGTH VARCHAR(29), 
    TEACHERS VARCHAR(10), 
    COMMENT VARCHAR(80));
COMMIT;