DROP TABLE tangoma_TEST_NYASIDANTK_TEXT;
CREATE TABLE tangoma_TEST_NYASIDANTK_TEXT(
   id INT NOT NULL AUTO_INCREMENT,
   PRIMARY KEY(id), 
   name VARCHAR(32) NOT NULL, 
   description TEXT NOT NULL 
);